### ISSUE TITLE
better support for ecto associations

### ISSUE THREAD

**Issue by sloanelybutsurely** [sloanelybutsurely/typeid-elixir#20]
when using a `belongs_to` field users must use `define_type: false` and specify a separate `_id` field with the appropriate prefix.

https://danschultzer.com/posts/prefixed-base62-uuidv7-object-ids-with-ecto has an example of using schema introspection to infer the prefix. we should do this.

maybe also add application config for default `type` values if a project uses exclusively `:string` or `:binary_id`

**Comment by clone1018** [comment]
Hey @sloanelybutsurely for those who haven't tried this library yet, can you provide an example of your what schema file looks like with the `belongs_to` & separate `_id` field?
