### ISSUE TITLE
parameterized type error, ecto compatibility

### ISSUE THREAD

**Issue by meantheory** [sloanelybutsurely/typeid-elixir#33]
attempting to update ecto dependencies caused an issue with parameterized type. Got following error attempting a `Repo.insert!`

`** (MatchError) no match of right hand side value: {:parameterized, {TypeID, %{type: :binary_id, prefix: "user", field: :id, schema: Click.Accounts.User, primary_key: true}}}
`
Release notes for Ecto version 3.12.0 included a potential incompatibilities section. https://hexdocs.pm/ecto/changelog.html#potential-incompatibilities

This reads in part as: [Ecto.ParameterizedType] Parameterized types are now represented internally as {:parameterized, {mod, state}}. While this representation is private, projects may have been relying on it, and therefore they need to adapt accordingly. Use [Ecto.ParameterizedType.init/2](https://hexdocs.pm/ecto/Ecto.ParameterizedType.html#init/2) to instantiate parameterized types.

The error I am getting and the potential incompatibility seem to match. Rolling back to a previous version of Ecto resolved the issue.

**Comment by sloanelybutsurely** [comment]
Fixed in #34
